### ISSUE TITLE
Can i get the python code for fetching the Role Assignments for a specific Service Principle

### ISSUE THREAD

**Issue by jamavinay** [Azure-Samples/compute-python-msi-vm#2]
Hello Everyone,

One of my client is looking for the list of role assignments for a specific principal irrespective of subscriptions in azure. The list may be like below.

TenantID | SubscriptionID | SubscriptionName | RBACRoleDefinitionName | DisplayName | ObjectType | Scope
-- | -- | -- | -- | -- | -- | --
Could anyone please help me on this to get the list of service principals .

Thanks in advance.

**Comment by lmazuel** [comment]
Hello,
Closing this issue, since you opened another one in the right place :)
Thanks
